<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Live catalog source: https://nukreationz.com/all-products/ (retrieved April 21, 2026)
     */
    public function run(): void
    {
        $this->call(DefaultProductCategorySeeder::class);

        $categoryIds = ProductCategory::query()->pluck('id', 'slug');

        foreach ($this->products() as $product) {
            $categorySlug = $product['category_slug'] ?? null;
            unset($product['category_slug']);

            Product::query()->updateOrCreate(
                ['name' => $product['name']],
                [
                    ...$product,
                    'product_category_id' => $categorySlug ? $categoryIds->get($categorySlug) : null,
                ]
            );
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function products(): array
    {
        return [
            $this->product([
                'category_slug' => 'business-cards',
                'name' => 'E-Complimentary Card Design',
                'moq' => 1,
                'price' => 30000,
                'short_description' => 'Professionally designed e-complimentary card for digital networking.',
                'description' => 'A custom e-complimentary card design with contact details and brand identity for digital sharing.',
                'paper_type' => 'Digital Design',
                'paper_size' => 'Digital Card',
                'finishing' => 'Share-ready PNG/PDF',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'business-cards',
                'name' => 'Professional Signature e-Card',
                'moq' => 1,
                'price' => 10000,
                'short_description' => 'Professional signature e-card for direct contact sharing.',
                'description' => 'Digital e-card with your business details, QR-ready format, and clean professional layout.',
                'paper_type' => 'Digital Design',
                'paper_size' => 'Digital Card',
                'finishing' => 'Share-ready PNG/PDF',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'business-cards',
                'name' => 'Square Business Cards (2 Sided)',
                'moq' => 100,
                'price' => 10000,
                'short_description' => 'Premium two-sided square business cards with optional rounded corners.',
                'description' => 'Two-sided square business cards produced in full color on matte stock for high-impact brand presentation.',
                'paper_type' => 'Matte Card Stock',
                'paper_size' => '2.5 x 2.5 in',
                'finishing' => 'Matte Lamination',
                'paper_density' => '300gsm',
                'is_featured' => true,
            ]),
            $this->product([
                'category_slug' => 'business-cards',
                'name' => 'Square Business Cards (1 Sided)',
                'moq' => 100,
                'price' => 8000,
                'short_description' => 'One-sided square business cards for minimal brand communication.',
                'description' => 'One-sided square business cards printed in full color with clean finishing and premium card feel.',
                'paper_type' => 'Matte Card Stock',
                'paper_size' => '2.5 x 2.5 in',
                'finishing' => 'Matte Lamination',
                'paper_density' => '300gsm',
            ]),
            $this->product([
                'category_slug' => 'business-cards',
                'name' => 'Two-Sided Business Cards',
                'moq' => 100,
                'price' => 14000,
                'short_description' => 'Two-sided standard business cards with premium lamination options.',
                'description' => 'Standard-size two-sided business cards for corporate and small business networking.',
                'paper_type' => 'Matte Card Stock',
                'paper_size' => '85 x 55 mm',
                'finishing' => 'Matte Lamination',
                'paper_density' => '300gsm',
                'is_featured' => true,
            ]),
            $this->product([
                'category_slug' => 'business-cards',
                'name' => 'One Sided Business Cards',
                'moq' => 100,
                'price' => 4499,
                'short_description' => 'Affordable one-sided business cards for quick brand visibility.',
                'description' => 'One-sided standard business cards, full color print, suitable for simple contact and promo cards.',
                'paper_type' => 'Matte Card Stock',
                'paper_size' => '85 x 55 mm',
                'finishing' => 'Matte Lamination',
                'paper_density' => '300gsm',
            ]),

            $this->product([
                'category_slug' => 'banners-large-format',
                'name' => 'A-Frames Signs',
                'moq' => 1,
                'price' => 80000,
                'short_description' => 'Portable A-frame signage for outdoor and indoor campaigns.',
                'description' => 'A2 A-frame signs with full-color print for directional messaging and storefront visibility.',
                'paper_type' => 'PVC',
                'paper_size' => 'A2',
                'finishing' => 'Mounted on Aluminum A-Frame',
                'paper_density' => 'N/A',
                'is_featured' => true,
            ]),
            $this->product([
                'category_slug' => 'banners-large-format',
                'name' => 'Backdrop Banners',
                'moq' => 1,
                'price' => 350000,
                'short_description' => 'Event backdrop banners with full stand setup.',
                'description' => 'Large event backdrops printed on flex material with aluminum stand options for ceremonies and brand events.',
                'paper_type' => 'Flex Banner',
                'paper_size' => '8 x 8 ft',
                'finishing' => 'Mounted with Aluminum Stand',
                'paper_density' => 'N/A',
                'is_featured' => true,
            ]),
            $this->product([
                'category_slug' => 'banners-large-format',
                'name' => 'Dummy Cheque',
                'moq' => 1,
                'price' => 40000,
                'short_description' => 'Oversized dummy cheques for events, competitions, and brand activations.',
                'description' => 'Custom oversized cheque boards printed in full color for award and donation events.',
                'paper_type' => 'SAV on Corex Board',
                'paper_size' => '3 x 1.5 ft',
                'finishing' => 'Board Mounted',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'banners-large-format',
                'name' => 'Flex Banners Large (7ft x 3ft)',
                'moq' => 1,
                'price' => 12000,
                'short_description' => 'Large flex banners for events and storefront promotions.',
                'description' => '7ft x 3ft flex banners with full-color print and eyelets for easy hanging.',
                'paper_type' => 'Flex Banner',
                'paper_size' => '7 x 3 ft',
                'finishing' => 'Eyelets/Grommets',
                'paper_density' => 'N/A',
                'size_price_options' => [
                    '7 x 3 ft' => 12000,
                    '2x quantity bundle' => 24000,
                    '5x quantity bundle' => 60000,
                ],
            ]),
            $this->product([
                'category_slug' => 'banners-large-format',
                'name' => 'Flex Banners Medium (5ft x 3ft)',
                'moq' => 1,
                'price' => 6000,
                'short_description' => 'Medium-size flex banners for compact campaign display.',
                'description' => '5ft x 3ft flex banners produced in full color with reinforced corners and grommets.',
                'paper_type' => 'Flex Banner',
                'paper_size' => '5 x 3 ft',
                'finishing' => 'Eyelets/Grommets',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'banners-large-format',
                'name' => 'Instagram Frame Boards',
                'moq' => 1,
                'price' => 40000,
                'short_description' => 'Custom event Instagram frame boards for photo moments.',
                'description' => 'Full-color branded Instagram frame boards for parties, weddings, and corporate events.',
                'paper_type' => 'SAV on Corex Board',
                'paper_size' => 'Custom Large Format',
                'finishing' => 'Board Cut and Mounted',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'banners-large-format',
                'name' => 'Roll Up Banners (Flex Material + Base)',
                'moq' => 1,
                'price' => 55000,
                'short_description' => 'Roll-up banner stands with flex media and hardware base.',
                'description' => 'Portable roll-up display banners for exhibitions and walk-in branding points.',
                'paper_type' => 'Flex Banner',
                'paper_size' => 'Standard Roll-Up',
                'finishing' => 'Mounted with Roll-Up Base',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'banners-large-format',
                'name' => 'Roll Up Banners (Solite Material + Base)',
                'moq' => 1,
                'price' => 65000,
                'short_description' => 'Premium roll-up banners with solite print media.',
                'description' => 'Roll-up banners produced on solite media and supplied with display base.',
                'paper_type' => 'Solite',
                'paper_size' => 'Standard Roll-Up',
                'finishing' => 'Mounted with Roll-Up Base',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'banners-large-format',
                'name' => 'Snapper Frame',
                'moq' => 1,
                'price' => 120000,
                'short_description' => 'Snapper frame displays for notices, posters, and menus.',
                'description' => 'Durable snapper frames for offices, restaurants, and public notice display points.',
                'paper_type' => 'PVC + Aluminum Frame',
                'paper_size' => 'A1/A2 Options',
                'finishing' => 'Framed Display',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'banners-large-format',
                'name' => 'Teardrop Banners (3ft by 8ft)',
                'moq' => 1,
                'price' => 80000,
                'short_description' => 'Teardrop flag banners for premium outdoor branding.',
                'description' => '3ft by 8ft teardrop banners with stand accessory, ideal for events and entrances.',
                'paper_type' => 'Flag Fabric',
                'paper_size' => '3 x 8 ft',
                'finishing' => 'Hemmed with Pole Pocket',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'banners-large-format',
                'name' => 'Waterbase Poster Signs',
                'moq' => 1,
                'price' => 150000,
                'short_description' => 'Waterbase poster signs for restaurants and retail entrances.',
                'description' => 'Heavy-duty waterbase signage stands with printed poster insert for outdoor use.',
                'paper_type' => 'PVC',
                'paper_size' => 'A1',
                'finishing' => 'Aluminum + Waterbase Stand',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'banners-large-format',
                'name' => 'X-Banner',
                'moq' => 1,
                'price' => 40000,
                'short_description' => 'Budget-friendly X-banner displays for quick campaigns.',
                'description' => 'Portable X-banner stands with full-color PVC print for conferences and point-of-sale display.',
                'paper_type' => 'PVC',
                'paper_size' => '60 x 160 cm',
                'finishing' => 'Mounted to X-Stand',
                'paper_density' => 'N/A',
            ]),

            $this->product([
                'category_slug' => 'branded-envelopes',
                'name' => 'DL (Small) Envelopes',
                'moq' => 500,
                'price' => 70000,
                'short_description' => 'DL branded envelopes for slim folded business correspondence.',
                'description' => 'Printed DL envelopes on bond stock for official letters and compact inserts.',
                'paper_type' => 'Bond Paper',
                'paper_size' => 'DL',
                'finishing' => 'Printed and Folded',
                'paper_density' => '100gsm',
            ]),
            $this->product([
                'category_slug' => 'branded-envelopes',
                'name' => 'C4 (Big A4) Envelopes',
                'moq' => 500,
                'price' => 1950,
                'short_description' => 'Large C4 envelopes for A4 document handling.',
                'description' => 'C4 branded envelopes suitable for invoices, proposals, and official document deliveries.',
                'paper_type' => 'Bond Paper',
                'paper_size' => 'C4',
                'finishing' => 'Printed and Folded',
                'paper_density' => '100gsm',
            ]),

            $this->product([
                'category_slug' => 'branded-notepads-and-jotters',
                'name' => 'Ankara Notepad',
                'moq' => 100,
                'price' => 350000,
                'short_description' => 'Ankara-themed branded notepad with stylish cover finishing.',
                'description' => 'Premium notepad with Ankara-inspired cover, ideal for corporate gifts and executive events.',
                'paper_type' => 'Ankara Cover + Bond Inner Pages',
                'paper_size' => 'A5',
                'finishing' => 'Spiral Binding',
                'paper_density' => '100gsm',
            ]),
            $this->product([
                'category_slug' => 'branded-notepads-and-jotters',
                'name' => 'Customized A5 Leather Notepad',
                'moq' => 50,
                'price' => 9750,
                'short_description' => 'A5 leather notepad for executive gifting and daily planning.',
                'description' => 'A5 leather cover notepad with customizable branding for events and office gifting.',
                'paper_type' => 'Leather Cover + Bond Inner Pages',
                'paper_size' => 'A5',
                'finishing' => 'Perfect Bound',
                'paper_density' => '100gsm',
            ]),
            $this->product([
                'category_slug' => 'branded-notepads-and-jotters',
                'name' => 'Customized A6 Leather Notepad',
                'moq' => 50,
                'price' => 8500,
                'short_description' => 'Compact A6 leather notepad for branded giveaways and field notes.',
                'description' => 'Pocket-friendly A6 leather notepad designed for quick notes and premium brand merchandising.',
                'paper_type' => 'Leather Cover + Bond Inner Pages',
                'paper_size' => 'A6',
                'finishing' => 'Perfect Bound',
                'paper_density' => '100gsm',
            ]),

            $this->product([
                'category_slug' => 'calendars',
                'name' => 'A5 Wall Calendar',
                'moq' => 100,
                'price' => 25000,
                'short_description' => 'Branded A5 wall calendar for year-round business visibility.',
                'description' => 'Full-color wall calendar print for offices, giveaways, and seasonal campaigns.',
                'paper_type' => 'Matte Paper',
                'paper_size' => 'A5',
                'finishing' => 'Wire-O Binding',
                'paper_density' => '250gsm',
            ]),

            $this->product([
                'category_slug' => 'caps-hats',
                'name' => 'Face Caps (New)',
                'moq' => 25,
                'price' => 25000,
                'short_description' => 'Branded face caps for campaigns, teams, and promotional events.',
                'description' => 'Custom face caps with logo imprint suitable for outdoor campaigns and uniforms.',
                'paper_type' => 'Cotton Twill',
                'paper_size' => 'Adjustable',
                'finishing' => 'Embroidery/Print Branding',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'caps-hats',
                'name' => 'Flat Peak Facecaps',
                'moq' => 25,
                'price' => 32000,
                'short_description' => 'Flat peak branded caps for streetwear and campaign branding.',
                'description' => 'Premium flat peak facecaps with custom logo branding for lifestyle promotions.',
                'paper_type' => 'Cotton Twill',
                'paper_size' => 'Adjustable',
                'finishing' => 'Embroidery/Print Branding',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'caps-hats',
                'name' => 'Trucker Caps',
                'moq' => 25,
                'price' => 28000,
                'short_description' => 'Custom trucker caps with breathable mesh and logo branding.',
                'description' => 'Branded trucker caps for events, roadshows, and product campaigns.',
                'paper_type' => 'Polyester Mesh + Cotton Front',
                'paper_size' => 'Adjustable',
                'finishing' => 'Print/Embroidery',
                'paper_density' => 'N/A',
            ]),

            $this->product([
                'category_slug' => 'gift-items-corporate-gifts',
                'name' => 'Branded Business Card Cases',
                'moq' => 20,
                'price' => 45000,
                'short_description' => 'Premium business card cases for executive and corporate gifting.',
                'description' => 'Custom branded business card cases with durable finish for boardroom and client gifting.',
                'paper_type' => 'Metal/Leather',
                'paper_size' => 'Card Case',
                'finishing' => 'UV DTF/Laser Engraving',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'gift-items-corporate-gifts',
                'name' => 'Branded Power Banks',
                'moq' => 20,
                'price' => 180000,
                'short_description' => 'Branded power banks for high-value marketing campaigns.',
                'description' => 'Corporate power banks customized with logos for executive events and promotions.',
                'paper_type' => 'ABS/Metal',
                'paper_size' => 'Standard',
                'finishing' => 'UV DTF/Laser Engraving',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'gift-items-corporate-gifts',
                'name' => 'Branded Wooden Clock',
                'moq' => 10,
                'price' => 95000,
                'short_description' => 'Wooden branded clocks for premium desk and office gifting.',
                'description' => 'Customized wooden clocks for executive gifts and commemorative corporate events.',
                'paper_type' => 'Wood',
                'paper_size' => 'Desk/Wall Variant',
                'finishing' => 'Laser Engraving',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'gift-items-corporate-gifts',
                'name' => 'Corporate Gift Box',
                'moq' => 10,
                'price' => 250000,
                'short_description' => 'Curated corporate gift box bundles for events and festive campaigns.',
                'description' => 'Branded corporate gift boxes with custom inserts and packaging options.',
                'paper_type' => 'Mixed Materials',
                'paper_size' => 'Custom Box',
                'finishing' => 'Custom Packaging',
                'paper_density' => 'N/A',
                'is_featured' => true,
            ]),
            $this->product([
                'category_slug' => 'gift-items-corporate-gifts',
                'name' => 'Custom Block Pads',
                'moq' => 100,
                'price' => 50000,
                'short_description' => 'Branded block pads for office desks and promotional kits.',
                'description' => 'Desktop block pads customized with business identity for daily office use.',
                'paper_type' => 'Bond Paper',
                'paper_size' => 'A6/A5 Options',
                'finishing' => 'Pad Glue Binding',
                'paper_density' => '100gsm',
            ]),
            $this->product([
                'category_slug' => 'gift-items-corporate-gifts',
                'name' => 'Custom Water Bottles',
                'moq' => 20,
                'price' => 95000,
                'short_description' => 'Reusable branded water bottles for teams and campaigns.',
                'description' => 'Durable customizable bottles for internal branding and giveaways.',
                'paper_type' => 'Aluminum/Plastic',
                'paper_size' => 'Standard Bottle',
                'finishing' => 'UV DTF/Laser Engraving',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'gift-items-corporate-gifts',
                'name' => 'Digital Luggage Scale',
                'moq' => 20,
                'price' => 75000,
                'short_description' => 'Branded digital luggage scales for practical gifting campaigns.',
                'description' => 'Portable digital luggage scales customized for travel and corporate appreciation kits.',
                'paper_type' => 'Plastic/Metal',
                'paper_size' => 'Portable',
                'finishing' => 'UV DTF',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'gift-items-corporate-gifts',
                'name' => 'Gift Box',
                'moq' => 20,
                'price' => 120000,
                'short_description' => 'Customizable gift boxes for premium packaging and campaigns.',
                'description' => 'Branded gift boxes for curated product sets and festive customer gifts.',
                'paper_type' => 'Hard Box Board',
                'paper_size' => 'Custom',
                'finishing' => 'Lamination and Ribbon',
                'paper_density' => '1200gsm',
            ]),
            $this->product([
                'category_slug' => 'gift-items-corporate-gifts',
                'name' => 'Mouse Pads As Corporate Gift',
                'moq' => 50,
                'price' => 45000,
                'short_description' => 'Custom mouse pads for practical office branding.',
                'description' => 'Office mouse pads branded with company identity for internal and customer gifting.',
                'paper_type' => 'Rubber + Fabric Top',
                'paper_size' => 'Standard',
                'finishing' => 'Sublimation Print',
                'paper_density' => 'N/A',
            ]),

            $this->product([
                'category_slug' => 'custom-mugs',
                'name' => 'Custom Mugs',
                'moq' => 12,
                'price' => 5000,
                'short_description' => 'Standard branded ceramic mugs with full-color customization.',
                'description' => 'Ceramic custom mugs for gifting, office use, and event souvenirs.',
                'paper_type' => 'Ceramic',
                'paper_size' => '11oz Standard',
                'finishing' => 'Full-Color Sublimation',
                'paper_density' => 'N/A',
                'is_featured' => true,
            ]),
            $this->product([
                'category_slug' => 'custom-mugs',
                'name' => 'Custom Magic Mugs',
                'moq' => 12,
                'price' => 10000,
                'short_description' => 'Heat-sensitive magic mugs that reveal custom designs.',
                'description' => 'Black ceramic mugs that reveal personalized artwork when hot liquid is added.',
                'paper_type' => 'Heat-Sensitive Ceramic',
                'paper_size' => '11oz Standard',
                'finishing' => 'Full-Color Sublimation',
                'paper_density' => 'N/A',
            ]),

            $this->product([
                'category_slug' => 'custom-t-shirts',
                'name' => 'Custom T-Shirts',
                'moq' => 20,
                'price' => 120000,
                'short_description' => 'Custom branded T-shirts for uniforms, events, and merch drops.',
                'description' => 'High-quality T-shirt branding for team wear, promotions, and campaign uniforms.',
                'paper_type' => 'Cotton Fabric',
                'paper_size' => 'S-XXL Assorted',
                'finishing' => 'DTF/Screen Print',
                'paper_density' => 'N/A',
                'is_featured' => true,
            ]),

            $this->product([
                'category_slug' => 'flyers-handbills',
                'name' => 'Flyers A4',
                'moq' => 500,
                'price' => 35000,
                'short_description' => 'A4 promotional flyers for product launches and events.',
                'description' => 'A4 flyer prints in full color for marketing campaigns and outreach.',
                'paper_type' => 'Matte Paper',
                'paper_size' => 'A4',
                'finishing' => 'Trim Cut',
                'paper_density' => '150gsm',
            ]),
            $this->product([
                'category_slug' => 'flyers-handbills',
                'name' => 'Handbills',
                'moq' => 500,
                'price' => 30000,
                'short_description' => 'Affordable handbills for street and event distribution.',
                'description' => 'Mass handbill printing for grassroots campaigns and awareness drives.',
                'paper_type' => 'Matte Paper',
                'paper_size' => 'A5',
                'finishing' => 'Trim Cut',
                'paper_density' => '150gsm',
            ]),
            $this->product([
                'category_slug' => 'flyers-handbills',
                'name' => 'Sports Programmes',
                'moq' => 200,
                'price' => 50000,
                'short_description' => 'Printed sports programme brochures for tournaments and events.',
                'description' => 'Multi-page event programme prints for sports fixtures and ceremonies.',
                'paper_type' => 'Matte Paper',
                'paper_size' => 'A5 Folded',
                'finishing' => 'Saddle Stitch',
                'paper_density' => '170gsm',
            ]),

            $this->product([
                'category_slug' => 'frames-wall-arts',
                'name' => 'Landscape Canvas',
                'moq' => 1,
                'price' => 60000,
                'short_description' => 'Landscape canvas wall art for decor and corporate spaces.',
                'description' => 'Custom landscape canvas prints stretched and ready for interior display.',
                'paper_type' => 'Canvas',
                'paper_size' => 'Custom',
                'finishing' => 'Stretched Frame',
                'paper_density' => 'N/A',
            ]),

            $this->product([
                'category_slug' => 'greeting-cards',
                'name' => 'Postcards (A6)',
                'moq' => 100,
                'price' => 15000,
                'short_description' => 'A6 postcards for announcements, invitations, and promotions.',
                'description' => 'A6 postcard prints with vibrant full-color output and sturdy card finish.',
                'paper_type' => 'Matte Card Stock',
                'paper_size' => 'A6',
                'finishing' => 'Trim Cut',
                'paper_density' => '300gsm',
            ]),
            $this->product([
                'category_slug' => 'greeting-cards',
                'name' => 'Ramadan Cards',
                'moq' => 100,
                'price' => 60000,
                'short_description' => 'Festive Ramadan greeting cards with customizable messaging.',
                'description' => 'Custom Ramadan card prints for personal and corporate appreciation.',
                'paper_type' => 'Matte Card Stock',
                'paper_size' => 'A6',
                'finishing' => 'Matte Lamination',
                'paper_density' => '300gsm',
            ]),
            $this->product([
                'category_slug' => 'greeting-cards',
                'name' => 'Square Christmas Cards',
                'moq' => 100,
                'price' => 60000,
                'short_description' => 'Square Christmas cards for holiday customer engagement.',
                'description' => 'Seasonal square cards for holiday campaigns, gratitude notes, and brand gifting.',
                'paper_type' => 'Matte Card Stock',
                'paper_size' => '5.8 x 5.8 in',
                'finishing' => 'Matte Lamination',
                'paper_density' => '300gsm',
            ]),
            $this->product([
                'category_slug' => 'greeting-cards',
                'name' => 'Thank You Cards',
                'moq' => 100,
                'price' => 60000,
                'short_description' => 'Thank-you cards for events, weddings, and customer gifts.',
                'description' => 'Elegant thank-you card prints for post-event and customer appreciation use.',
                'paper_type' => 'Matte Card Stock',
                'paper_size' => 'A6',
                'finishing' => 'Matte Lamination',
                'paper_density' => '300gsm',
            ]),

            $this->product([
                'category_slug' => 'letterhead',
                'name' => 'Continuation Sheets',
                'moq' => 500,
                'price' => 90000,
                'short_description' => 'Branded continuation sheets to match your official letterhead.',
                'description' => 'A4 continuation sheets with company identity for proposal and documentation consistency.',
                'paper_type' => 'Matte Paper',
                'paper_size' => 'A4',
                'finishing' => 'Trim Cut',
                'paper_density' => '150gsm',
            ]),

            $this->product([
                'category_slug' => 'marketing-brochures',
                'name' => 'A4 Trifold Brochures',
                'moq' => 200,
                'price' => 65000,
                'short_description' => 'A4 trifold brochures for detailed product and service marketing.',
                'description' => 'Tri-fold brochures suitable for menus, company profiles, and campaign handouts.',
                'paper_type' => 'Matte Paper',
                'paper_size' => 'A4 Trifold',
                'finishing' => 'Creasing and Folding',
                'paper_density' => '170gsm',
            ]),

            $this->product([
                'category_slug' => 'paper-bags',
                'name' => 'Large Paper Bags A3',
                'moq' => 100,
                'price' => 120000,
                'short_description' => 'A3 branded paper bags for retail and event packaging.',
                'description' => 'Large branded paper bags with durable finishing for product handover and promotions.',
                'paper_type' => 'Art Card',
                'paper_size' => 'A3',
                'finishing' => 'Laminated with Rope Handles',
                'paper_density' => '250gsm',
            ]),
            $this->product([
                'category_slug' => 'paper-bags',
                'name' => 'Pillow Bags A4',
                'moq' => 100,
                'price' => 85000,
                'short_description' => 'A4 pillow bags for premium product packaging.',
                'description' => 'Printed A4 pillow bags with neat fold and brand customization options.',
                'paper_type' => 'Art Card',
                'paper_size' => 'A4',
                'finishing' => 'Die Cut and Fold',
                'paper_density' => '250gsm',
            ]),
            $this->product([
                'category_slug' => 'paper-bags',
                'name' => 'Pillow Bags A5',
                'moq' => 100,
                'price' => 70000,
                'short_description' => 'Compact A5 pillow bags for gift and souvenir packaging.',
                'description' => 'A5 pillow bags with clean finishing for boutique and event product packaging.',
                'paper_type' => 'Art Card',
                'paper_size' => 'A5',
                'finishing' => 'Die Cut and Fold',
                'paper_density' => '250gsm',
            ]),

            $this->product([
                'category_slug' => 'phone-cases',
                'name' => 'Custom Slim (All Clear) Phone Cases',
                'moq' => 10,
                'price' => 25000,
                'short_description' => 'All-clear slim phone cases with custom print branding.',
                'description' => 'Transparent slim-fit phone case customization for brand gifts and merch.',
                'paper_type' => 'Polycarbonate',
                'paper_size' => 'Phone Model Specific',
                'finishing' => 'UV Print',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'phone-cases',
                'name' => 'Custom Clear iPhone Cases',
                'moq' => 10,
                'price' => 30000,
                'short_description' => 'Custom clear iPhone cases with durable print finish.',
                'description' => 'Personalized clear iPhone cases for gifting, reselling, and event branding.',
                'paper_type' => 'Polycarbonate',
                'paper_size' => 'iPhone Model Specific',
                'finishing' => 'UV Print',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'phone-cases',
                'name' => 'Phone Cases (Google Pixel)',
                'moq' => 10,
                'price' => 30000,
                'short_description' => 'Google Pixel custom case printing for brand personalization.',
                'description' => 'Custom Google Pixel case production with photo, logo, and campaign artwork options.',
                'paper_type' => 'Polycarbonate',
                'paper_size' => 'Pixel Model Specific',
                'finishing' => 'UV Print',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'phone-cases',
                'name' => 'Phone Cases (Huawei)',
                'moq' => 10,
                'price' => 30000,
                'short_description' => 'Huawei phone case branding for custom merch and gifts.',
                'description' => 'Custom Huawei cases with high-resolution logo and photo application.',
                'paper_type' => 'Polycarbonate',
                'paper_size' => 'Huawei Model Specific',
                'finishing' => 'UV Print',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'phone-cases',
                'name' => 'Phone Cases (iPhone)',
                'moq' => 10,
                'price' => 32000,
                'short_description' => 'Custom iPhone case printing for premium personalization.',
                'description' => 'High-quality iPhone case customization for business gifting and retail sales.',
                'paper_type' => 'Polycarbonate',
                'paper_size' => 'iPhone Model Specific',
                'finishing' => 'UV Print',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'phone-cases',
                'name' => 'Phone Cases (Samsung)',
                'moq' => 10,
                'price' => 30000,
                'short_description' => 'Samsung phone case custom print service with durable output.',
                'description' => 'Custom Samsung case printing for personal and corporate use cases.',
                'paper_type' => 'Polycarbonate',
                'paper_size' => 'Samsung Model Specific',
                'finishing' => 'UV Print',
                'paper_density' => 'N/A',
            ]),

            $this->product([
                'category_slug' => 'plastic-identity-cards',
                'name' => 'Landscape Identity Cards',
                'moq' => 50,
                'price' => 5500,
                'short_description' => 'Landscape PVC identity cards for staff and event accreditation.',
                'description' => 'Custom landscape ID cards with template and branding support for organizations.',
                'paper_type' => 'PVC Plastic',
                'paper_size' => 'CR80',
                'finishing' => 'Full-Color Card Print',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'plastic-identity-cards',
                'name' => 'Portrait Identity Cards with Lanyard (Coloured Back)',
                'moq' => 50,
                'price' => 8500,
                'short_description' => 'Portrait PVC ID cards with lanyard and branded back.',
                'description' => 'Portrait ID cards with lanyard accessories for teams, schools, and events.',
                'paper_type' => 'PVC Plastic',
                'paper_size' => 'CR80',
                'finishing' => 'Full-Color Card Print + Lanyard',
                'paper_density' => 'N/A',
            ]),

            $this->product([
                'category_slug' => 'presentation-folders',
                'name' => 'Presentation Folders',
                'moq' => 100,
                'price' => 85000,
                'short_description' => 'Branded presentation folders for proposals and corporate documents.',
                'description' => 'Custom presentation folders with pockets for pitches, onboarding packs, and events.',
                'paper_type' => 'Art Card',
                'paper_size' => 'A4 Folder',
                'finishing' => 'Die Cut and Creased',
                'paper_density' => '350gsm',
            ]),

            $this->product([
                'category_slug' => 'posters',
                'name' => 'A1 Posters',
                'moq' => 20,
                'price' => 65000,
                'short_description' => 'A1 posters for high-visibility campaign messaging.',
                'description' => 'Full-color A1 posters suitable for events, announcements, and storefront promotions.',
                'paper_type' => 'Matte Paper',
                'paper_size' => 'A1',
                'finishing' => 'Trim Cut',
                'paper_density' => '150gsm',
            ]),
            $this->product([
                'category_slug' => 'posters',
                'name' => 'A2 Posters',
                'moq' => 20,
                'price' => 55000,
                'short_description' => 'A2 posters for event and in-store promotional campaigns.',
                'description' => 'A2 poster prints with rich color output and clean finishing.',
                'paper_type' => 'Matte Paper',
                'paper_size' => 'A2',
                'finishing' => 'Trim Cut',
                'paper_density' => '150gsm',
            ]),
            $this->product([
                'category_slug' => 'posters',
                'name' => 'A3 Posters',
                'moq' => 20,
                'price' => 40000,
                'short_description' => 'A3 posters for compact awareness and campaign messaging.',
                'description' => 'A3 poster prints with full-color clarity for office, retail, and public notice usage.',
                'paper_type' => 'Matte Paper',
                'paper_size' => 'A3',
                'finishing' => 'Trim Cut',
                'paper_density' => '150gsm',
            ]),
            $this->product([
                'category_slug' => 'posters',
                'name' => 'Large Posters A0',
                'moq' => 10,
                'price' => 90000,
                'short_description' => 'Large A0 posters for outdoor and high-footfall locations.',
                'description' => 'A0 oversized posters ideal for large promotions, directional signage, and event branding.',
                'paper_type' => 'Matte Paper',
                'paper_size' => 'A0',
                'finishing' => 'Trim Cut',
                'paper_density' => '150gsm',
            ]),

            $this->product([
                'category_slug' => 'stickers',
                'name' => 'Bumper Stickers (7\" x 3\")',
                'moq' => 100,
                'price' => 25000,
                'short_description' => 'Durable bumper stickers for vehicle and campaign branding.',
                'description' => '7 x 3 inch bumper stickers with weather-resistant adhesive print.',
                'paper_type' => 'Vinyl Sticker',
                'paper_size' => '7 x 3 in',
                'finishing' => 'Die Cut',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'stickers',
                'name' => 'Round Stickers (3.5\" Diameter)',
                'moq' => 100,
                'price' => 22000,
                'short_description' => 'Round custom stickers for packaging and product labeling.',
                'description' => '3.5-inch round stickers printed in full color on adhesive stock.',
                'paper_type' => 'Vinyl Sticker',
                'paper_size' => '3.5 in Diameter',
                'finishing' => 'Die Cut',
                'paper_density' => 'N/A',
            ]),
            $this->product([
                'category_slug' => 'stickers',
                'name' => 'Square Stickers (3.5\" x 3.5\")',
                'moq' => 100,
                'price' => 22000,
                'short_description' => 'Square stickers for product packaging and brand seals.',
                'description' => '3.5 x 3.5 inch square sticker prints suitable for retail and promotional packaging.',
                'paper_type' => 'Vinyl Sticker',
                'paper_size' => '3.5 x 3.5 in',
                'finishing' => 'Die Cut',
                'paper_density' => 'N/A',
            ]),

            $this->product([
                'category_slug' => 'tote-bags',
                'name' => 'Branded A3 Tote Bags',
                'moq' => 50,
                'price' => 95000,
                'short_description' => 'A3 tote bags for event packs, shopping, and campaign branding.',
                'description' => 'Durable branded tote bags with ample capacity for retail and promotional events.',
                'paper_type' => 'Canvas Fabric',
                'paper_size' => 'A3 Capacity',
                'finishing' => 'DTF/Screen Print',
                'paper_density' => 'N/A',
            ]),

            $this->product([
                'category_slug' => 'wedding-stationery',
                'name' => 'Save The Date (A6 sizes)',
                'moq' => 100,
                'price' => 45000,
                'short_description' => 'A6 save-the-date cards for weddings and pre-event announcements.',
                'description' => 'Elegant save-the-date card prints with personalized design and premium stock.',
                'paper_type' => 'Matte Card Stock',
                'paper_size' => 'A6',
                'finishing' => 'Matte Lamination',
                'paper_density' => '300gsm',
            ]),
            $this->product([
                'category_slug' => 'wedding-stationery',
                'name' => 'Wedding Invitation',
                'moq' => 100,
                'price' => 85000,
                'short_description' => 'Custom wedding invitation cards with premium print finishing.',
                'description' => 'Personalized wedding invitations with envelope and optional premium finishing.',
                'paper_type' => 'Matte Card Stock',
                'paper_size' => 'A5/A6 Options',
                'finishing' => 'Matte/Gloss Lamination',
                'paper_density' => '300gsm',
                'is_featured' => true,
            ]),
        ];
    }

    /**
     * @param  array<string, mixed>  $attributes
     * @return array<string, mixed>
     */
    private function product(array $attributes): array
    {
        return array_replace([
            'category_slug' => null,
            'name' => '',
            'moq' => 1,
            'price' => 0,
            'short_description' => '',
            'description' => '',
            'paper_type' => 'Other',
            'paper_size' => 'Custom',
            'finishing' => 'No Finish',
            'paper_density' => 'N/A',
            'material_price_options' => null,
            'size_price_options' => null,
            'finish_price_options' => null,
            'density_price_options' => null,
            'delivery_price_options' => null,
            'featured_image' => null,
            'additional_images' => [],
            'is_active' => true,
            'is_featured' => false,
        ], $attributes);
    }
}
