<?php

return [
    'roles' => [
        'super_admin' => ['*'],
        'admin' => ['*'],
        'it' => ['*'],
        'management' => ['*'],
        'hr' => ['admin.view', 'orders.view', 'staff.view', 'announcements.view', 'blog.view', 'evaluations.view'],
        'operations' => ['admin.view', 'orders.view', 'orders.verify', 'orders.phase_comment', 'workflow.approve', 'sop.verify', 'invoices.manage'],
        'operations_manager' => ['admin.view', 'orders.view', 'orders.verify', 'orders.phase_comment', 'workflow.approve', 'sop.verify', 'invoices.manage'],
        'supervisor' => ['admin.view', 'orders.view', 'orders.verify', 'orders.phase_comment', 'workflow.approve', 'staff.view', 'sop.verify'],
        'customer_service' => ['admin.view', 'orders.view', 'orders.create', 'orders.intake', 'invoices.manage', 'delivery.update', 'client_review.update', 'sop.update', 'newsletters.manage'],
        'marketing' => ['admin.view', 'newsletters.manage'],
        'designer' => ['admin.view', 'orders.view', 'design.update', 'design.upload'],
        'finance' => ['admin.view', 'orders.view', 'finance.view', 'finance.create', 'finance.update', 'finance.delete', 'finance.view_amounts', 'invoices.manage'],
        'production' => ['admin.view', 'orders.view', 'production.update', 'packaging.update'],
        'operator' => ['admin.view', 'orders.view', 'production.update', 'packaging.update'],
        'qc' => ['admin.view', 'orders.view', 'qc.update'],
        'logistics' => ['admin.view', 'orders.view', 'delivery.update'],
        'staff_pending' => [],
    ],

    'role_priority' => [
        'super_admin' => 100,
        'admin' => 95,
        'it' => 95,
        'management' => 90,
        'operations_manager' => 85,
        'supervisor' => 80,
        'operations' => 75,
        'customer_service' => 70,
        'marketing' => 68,
        'finance' => 65,
        'qc' => 60,
        'production' => 50,
        'operator' => 50,
        'designer' => 40,
        'hr' => 35,
        'logistics' => 30,
        'staff_pending' => 5,
        'customer' => 0,
    ],

    'role_labels' => [
        'super_admin' => 'Super Admin',
        'management' => 'Management',
        'admin' => 'Admin',
        'it' => 'IT',
        'hr' => 'HR',
        'operations' => 'Operations',
        'operations_manager' => 'Operations Manager',
        'supervisor' => 'Supervisor',
        'customer_service' => 'Customer Service',
        'marketing' => 'Marketing',
        'designer' => 'Designer',
        'finance' => 'Finance',
        'production' => 'Production Staff',
        'operator' => 'Operator',
        'qc' => 'QC Officer',
        'logistics' => 'Logistics / Dispatch',
        'staff_pending' => 'Pending Staff',
    ],

    'departments' => [
        'management' => 'Management',
        'hr' => 'HR',
        'it' => 'IT',
        'operations' => 'Operations',
        'supervision' => 'Supervision',
        'customer_service' => 'Customer Service',
        'marketing' => 'Marketing',
        'design' => 'Design',
        'finance' => 'Finance',
        'production' => 'Production',
        'quality_control' => 'Quality Control',
        'logistics' => 'Logistics',
    ],

    'staff_signup_roles' => [
        'hr' => 'HR',
        'it' => 'IT',
        'operations' => 'Operations',
        'operations_manager' => 'Operations Manager',
        'customer_service' => 'Customer Service',
        'marketing' => 'Marketing',
        'designer' => 'Designer',
        'operator' => 'Operator',
        'qc' => 'QC',
        'finance' => 'Finance',
        'other' => 'Other',
    ],

    'staff_dashboard_menus' => [
        'hr' => ['Staff Information', 'Announcements', 'Monthly Evaluations', 'Job Information'],
        'it' => ['All Data', 'Staff Approvals', 'Jobs', 'Invoices', 'Finance', 'Settings'],
        'super_admin' => ['All Data', 'Staff Approvals', 'Jobs', 'Invoices', 'Finance', 'Settings'],
        'admin' => ['All Data', 'Staff Approvals', 'Jobs', 'Invoices', 'Finance', 'Settings'],
        'operations' => ['Job Process', 'Phase Approvals', 'Production Comments'],
        'operations_manager' => ['Job Process', 'Phase Approvals', 'Production Comments'],
        'customer_service' => ['Customer Data', 'Job Information', 'Invoices', 'Job Cards'],
        'marketing' => ['Newsletter Campaigns', 'Client Reach', 'Campaign Reports'],
        'designer' => ['Job Briefs', 'Design Feedback', 'Uploads'],
        'qc' => ['Job Information', 'Client Delivery Details', 'Final Design Review', 'Delivery/Return Status'],
        'finance' => ['Invoices', 'Job Information', 'Finance Operations', 'Payment Records'],
        'production' => ['Production Jobs', 'Packaging'],
        'operator' => ['Production Jobs', 'Packaging'],
    ],

    'module_permissions' => [
        'products.manage' => 'Product Management',
        'product_categories.manage' => 'Product Category Management',
        'blog.manage' => 'Blog Management',
        'invoices.manage' => 'Invoice Management',
        'newsletters.manage' => 'Newsletter Campaigns',
        'finance.view' => 'Finance',
        'site_settings.manage' => 'Site Settings',
    ],

    'job_statuses' => [
        'Quote Requested',
        'Analyzing Job Brief',
        'Design / Artwork Preparation',
        'In Production',
        'Quality Check & Packaging',
        'Delivery In Progress',
        'Delivered',
        'Client Review — Satisfactory',
        'After-Sales: Revision Requested',
        'After-Sales: Reprint Required',
        'On Hold',
        'Cancelled',
    ],

    'job_types' => [
        'Business Cards',
        'Flyers',
        'Banners',
        'Roll-Up Banner',
        'Letterheads',
        'Compliment Slips',
        'Branding Kit',
        'ID Cards',
        'Stickers',
        'T-Shirt Print',
        'Engraving',
        'UV DTF',
        'DTF prints',
        'Jotters',
        'Calendar',
        'Other',
    ],

    'sizes' => [
        'A3',
        'A4',
        'A5',
        'A6',
        'DL',
        '85x55mm (Business Card)',
        'Custom — see notes',
    ],

    'materials' => [
        'Art Paper 90gsm',
        'Art Paper 115gsm',
        'Art Paper 150gsm',
        'Art Paper 200gsm',
        'Art Card 250gsm',
        'Art Card 300gsm',
        'Art Card 350gsm',
        'Vinyl',
        'PVC',
        'Fabric',
        'Cotton',
        'Aluminium',
        'Wood',
        'Acrylic',
        'Flex banner',
        'Other',
    ],

    'finishes' => [
        'Gloss Lamination',
        'Matt Lamination',
        'Spot UV',
        'No Finish',
        'Embossing',
        'Foil Stamping',
        'Perforation',
        'Spiral Binding',
        'Saddle Stitch',
        'Perfect Bind',
    ],

    'payment_statuses' => [
        'Awaiting Invoice',
        'Invoice Issued',
        'Pending Payment',
        'Invoice Settled (70%)',
        'Invoice Settled (100%)',
    ],

    'priorities' => [
        '🔴 Urgent',
        '🟡 Normal',
        '🟢 Low',
    ],

    'job_channels' => [
        'Online',
        'Manual',
        'Walk-in Client',
    ],

    'delivery_methods' => [
        'Client Pickup',
        'Dispatch Rider',
    ],

    'review_statuses' => [
        'Pending Client Feedback',
        'Client Satisfied ✅',
        'Revision Requested 🔄',
        'Reprint Required 🔁',
        'Escalated ⚠️',
    ],

    'workflow_phases' => [
        [
            'phase' => '1 — Intake',
            'status' => 'Analyzing Job Brief',
            'responsible' => 'Customer Service',
            'permission' => 'orders.intake',
            'fields' => ['job_order_number', 'channel', 'job_type', 'size_format', 'priority', 'brief_received_by_id', 'brief_received_at', 'assigned_designer_id', 'artwork_notes', 'job_image_assets', 'internal_notes'],
            'gates' => [
                'Receive and acknowledge client enquiry within 2 hours.',
                'Collect complete brief: type, size, quantity, deadline, reference files.',
                'Assign Job Order # using PB-YYYY-XXXX and log the job before work begins.',
                'Issue quote, create invoice, and collect 70% deposit before production.',
            ],
        ],
        [
            'phase' => '2 — Design',
            'status' => 'Design / Artwork Preparation',
            'responsible' => 'Designer / Customer Service',
            'permission' => 'design.update',
            'fields' => ['status', 'design_started_at', 'design_approved_by_client', 'design_approved_at', 'final_design_path', 'internal_notes'],
            'gates' => [
                'Designer confirms brief receipt and logs Design Start Date.',
                'Prepare print-ready artwork with 3mm bleed, CMYK colour, and 300dpi+ resolution.',
                'Send proof to client and save documented approval before production.',
            ],
        ],
        [
            'phase' => '3 — Production',
            'status' => 'In Production',
            'responsible' => 'Production / Management',
            'permission' => 'production.update',
            'fields' => ['status', 'production_officer_id', 'production_started_at', 'material_substrate', 'finish_lamination', 'internal_notes'],
            'gates' => [
                'Receive approved artwork from Design and confirm print readiness.',
                'Confirm material/substrate is available or raise a purchase order.',
                'Confirm 70% payment before starting production.',
                'Run a test print, complete production, and verify output quantity.',
            ],
        ],
        [
            'phase' => '4 — QC & Packaging',
            'status' => 'Quality Check & Packaging',
            'responsible' => 'QC Officer / Production',
            'permission' => 'qc.update',
            'fields' => ['status', 'qc_checked_by_id', 'qc_checked_at', 'qc_result', 'internal_notes'],
            'gates' => [
                'Inspect all units against the approved proof for colour, trim, finish, and quantity.',
                'If QC fails, log the issue and initiate reprint.',
                'Package approved jobs and label with client name, job number, and delivery date.',
            ],
        ],
        [
            'phase' => '5 — Delivery',
            'status' => 'Delivery In Progress',
            'responsible' => 'Customer Service / Logistics',
            'permission' => 'delivery.update',
            'fields' => ['status', 'estimated_delivery_at', 'actual_delivery_at', 'delivery_method', 'dispatched_by_id', 'internal_notes'],
            'gates' => [
                'Confirm 100% payment or agreed terms before dispatch.',
                'Notify client that the job is ready or on its way.',
                'Log delivery method, dispatcher, actual delivery date, and delivered status.',
            ],
        ],
        [
            'phase' => '6 — Client Review',
            'status' => 'Client Review — Satisfactory',
            'responsible' => 'Customer Service / Management',
            'permission' => 'client_review.update',
            'fields' => ['status', 'client_review_status', 'after_sales_action', 'after_sales_resolved_at', 'internal_notes'],
            'gates' => [
                'Follow up with client 24 hours after delivery.',
                'Close satisfied jobs, or log revision/reprint issue and owner.',
                'Resolve after-sales issue and confirm client satisfaction.',
            ],
        ],
    ],
];
