@extends('layouts.theme')

@section('title', 'Finance | Printbuka')

@section('content')
    <main class="bg-slate-50 py-12 text-slate-900"><section class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-black uppercase tracking-wide text-pink-700">Finance</p><h1 class="mt-2 text-4xl text-slate-950">Cash flow.</h1></div><a href="{{ route('admin.finance.create') }}" class="rounded-md bg-pink-600 px-5 py-3 text-sm font-black text-white transition hover:bg-pink-700">Add Entry</a></div>
        <div class="mt-8 grid gap-5 sm:grid-cols-3"><div class="rounded-md border border-slate-200 bg-white p-6 shadow-sm"><p class="text-sm font-black uppercase tracking-wide text-emerald-700">Income</p><p class="mt-3 text-3xl font-black">NGN {{ number_format((float) $income, 2) }}</p></div><div class="rounded-md border border-slate-200 bg-white p-6 shadow-sm"><p class="text-sm font-black uppercase tracking-wide text-pink-700">Expenses</p><p class="mt-3 text-3xl font-black">NGN {{ number_format((float) $expenses, 2) }}</p></div><div class="rounded-md border border-slate-200 bg-white p-6 shadow-sm"><p class="text-sm font-black uppercase tracking-wide text-cyan-700">Net</p><p class="mt-3 text-3xl font-black">NGN {{ number_format((float) $income - (float) $expenses, 2) }}</p></div></div>
        @if (session('status'))<p class="mt-6 rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">{{ session('status') }}</p>@endif
        <div class="mt-8 overflow-x-auto rounded-md border border-slate-200 bg-white shadow-sm"><table class="w-full min-w-[900px] text-left text-sm"><thead><tr class="border-b border-slate-200 bg-slate-50 text-xs font-black uppercase tracking-wide text-slate-500"><th class="px-5 py-4">Date</th><th class="px-5 py-4">Type</th><th class="px-5 py-4">Category</th><th class="px-5 py-4">Description</th><th class="px-5 py-4">Amount</th><th class="px-5 py-4"></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($entries as $entry)<tr><td class="px-5 py-4">{{ $entry->entry_date->format('M j, Y') }}</td><td class="px-5 py-4">{{ ucfirst($entry->type) }}</td><td class="px-5 py-4">{{ $entry->category }}</td><td class="px-5 py-4">{{ $entry->description }}</td><td class="px-5 py-4">NGN {{ number_format((float) $entry->amount, 2) }}</td><td class="px-5 py-4 text-right"><a href="{{ route('admin.finance.edit', $entry) }}" class="font-black text-pink-700">Edit</a><form action="{{ route('admin.finance.destroy', $entry) }}" method="POST" class="inline">@csrf @method('DELETE') <button class="ml-4 font-black text-slate-500 hover:text-red-700">Delete</button></form></td></tr>@empty<tr><td colspan="6" class="px-5 py-10 text-center text-slate-500">No finance entries yet.</td></tr>@endforelse</tbody></table></div>
        <div class="mt-6">{{ $entries->links() }}</div>
    </section></main>
@endsection
